### ISSUE TITLE
Email Corespondence

### ISSUE THREAD

**Issue by ItsPugle** [nadiajoyce/nadiajoyce.github.io#1]
Hey @nadiajoyce,

I'm really sorry to have to reach out to you this way! This is the only way I could think of without contacting you through your photography-freelancer address. Is their a `@github.com` email I can reach you on about the [GitHub Community](https://github.community)?

Cheers!

**Comment by nadiajoyce** [comment]
@ItsPugle If you have something to want to discuss with the Community Forum team, you can send an email to community@github.com or use the Support [contact form](git.io/c).

**Comment by ItsPugle** [comment]
Cheers, Nadia! Sorry once again
